        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 17 10:02:27 2012
        MODULE CSTATN__genmod
          INTERFACE 
            SUBROUTINE CSTATN
            END SUBROUTINE CSTATN
          END INTERFACE 
        END MODULE CSTATN__genmod
